# Generated by Django 5.1 on 2024-09-09 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('initial_price', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('players', models.ManyToManyField(to='app.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('match_date', models.DateTimeField()),
                ('team_a_goal', models.IntegerField(default=0)),
                ('team_b_goal', models.IntegerField(default=0)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a_matches', to='app.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b_matches', to='app.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('minutes', models.IntegerField()),
                ('action', models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow card', 'Yellow Card'), ('red card', 'Red Card')], max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
