# Generated by Django 5.1 on 2024-09-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Ação do jogo', 'verbose_name_plural': 'Ações do jogo'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
        migrations.AlterModelOptions(
            name='myteam',
            options={'verbose_name': 'Meu time', 'verbose_name_plural': 'Meus times'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('goal', 'Gol'), ('assist', 'Assistência'), ('yellow card', 'Cartão amarelo'), ('red card', 'Cartão vermelho')], max_length=50, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='action',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.match', verbose_name='Jogo'),
        ),
        migrations.AlterField(
            model_name='action',
            name='minutes',
            field=models.IntegerField(verbose_name='Minutos'),
        ),
        migrations.AlterField(
            model_name='action',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.player', verbose_name='Jogador'),
        ),
        migrations.AlterField(
            model_name='action',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(verbose_name='Data do jogo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a_matches', to='app.team', verbose_name='Time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_goal',
            field=models.IntegerField(default=0, verbose_name='Gols do Time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b_matches', to='app.team', verbose_name='Time B'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_goal',
            field=models.IntegerField(default=0, verbose_name='Gols do Time B'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='players',
            field=models.ManyToManyField(to='app.player', verbose_name='Jogadores'),
        ),
        migrations.AlterField(
            model_name='player',
            name='initial_price',
            field=models.FloatField(verbose_name='Preço inicial'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
