# Generated by Django 5.1 on 2024-09-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='minute',
            new_name='minutes',
        ),
    ]
